// Code generated by schema-generate. DO NOT EDIT.

package messages

// SnapServiceMessage A representation of collection of snap services to start/stop/restart
type SnapServiceMessage struct {

  // A list of services within the snap to take action on (or empty to apply to all)
  Services []string `json:"services,omitempty"`
}
